### ISSUE TITLE
# Design for Homepage 

### ISSUE THREAD

**Issue by hkaur008** [CodeFlow201/codeflow#1]
Color Palette 👍🏻 : https://colorhunt.co/palette/252800

**Comment by hkaur008** [comment]
**THE FRONT PAGE**
![Web 1920 – 1](https://user-images.githubusercontent.com/56452820/106878316-d15a9400-66ff-11eb-8f1d-4193548eb6c0.png)
### **Assets**
https://drive.google.com/drive/folders/1Vy84V-foh_1AKiWp5EGrCBEyqFi0HwWz?usp=sharing

**Comment by at-syot** [comment]
Hello.
Look nice design.
What is project about ?
What can i help ?

**Comment by hkaur008** [comment]
> Hello.
> Look nice design.
> What is project about ?
> What can i help ?

Actually this a MERN based site of our organization !!
This is design of home component  .

1.  DO A FORK 

You can use assets  in drive and design a responsive home component as looks in design.
 
2. MAKE A PULL REQUEST!!

**Comment by mostlypanda** [comment]
I'll love to design this one for Codeflow

**Comment by iamparasbansal** [comment]
I'll like to work on this

**Comment by iamparasbansal** [comment]
It's done and merged. Request to close this issue.

**Comment by mostlypanda** [comment]
Hyy guyz, Kindly review your main page as according to my review it's need many improvement and firstly some more sections to be added so that user can get the overview of us. Interested one ping me here for further direction
