### ISSUE TITLE
Contact us Page

### ISSUE THREAD

**Issue by mostlypanda** [CodeFlow201/codeflow#10]
This page is one of the great importance as this is the only place where user can interact to us, So before designing this one keep following points in your mind.

- This page will have some basic content at the top and will have a well animated form which will have some basic transition and animations. It's bg to be decided accordingly with header and footer.
- Proper Validation of the form
- Implement it's backend for frontend too which means when user filled up all details and submit it, a POST api will be called and data is to be saved

**Comment by Nirpendra09** [comment]
I would Like to work on this issue. Please Assign it to me

**Comment by mostlypanda** [comment]
Ya sure @Nirpendra09  go ahead with the ideation that is proposed above. Only keep one thing in mind that is of the color of the components that you will use and try to make all customized one.
Happy Coding!!!

**Comment by mita13** [comment]
I would like to take this issue.

**Comment by Mahek-26** [comment]
I would like to take this issue.

**Comment by mostlypanda** [comment]
@mita13  and @Mahek-26  guyz see as you both want to work over this component so I request you both to design your page accordingly and who so ever done a great thing we will incorporated her changes into website and also give other one some component to create no issue with that, so just fork down the repo and start working
