### ISSUE TITLE
Text overflowing in top contributors 

### ISSUE THREAD

**Issue by hkaur008** [CodeFlow201/codeflow#115]
![image](https://user-images.githubusercontent.com/56452820/136645331-f832b171-3ebe-48d4-86d6-2d18219dbef5.png)
Text should wrap inside card

**Comment by rktejesh** [comment]
@hkaur008 can u assign me this issue?

**Comment by hkaur008** [comment]
Sure

**Comment by IspadeRaja** [comment]
**Fixed Issue** and raised [#PR 116](https://github.com/CodeFlow201/codeflow/pull/116)

**Comment by hkaur008** [comment]
Okay i will check it out
