### ISSUE TITLE
different size of event cards on event page

### ISSUE THREAD

**Issue by Yashnatani021-coder** [CodeFlow201/codeflow#19]

**Comment by faisalalik9** [comment]
Issue resolved!

![Screenshot 2021-04-01 001227](https://user-images.githubusercontent.com/66014401/113197670-9188d680-9282-11eb-853a-950e83ab60cd.jpg)
![Screenshot 2021-04-01 001302](https://user-images.githubusercontent.com/66014401/113197686-951c5d80-9282-11eb-89f0-0a0cb3b2f77d.jpg)
