### ISSUE TITLE
#design of homepage - bottom section / about

### ISSUE THREAD

**Issue by hkaur008** [CodeFlow201/codeflow#2]
![about us](https://user-images.githubusercontent.com/56452820/108229282-acd1d380-7165-11eb-8b25-2679794eec50.jpg)

assets : https://drive.google.com/drive/folders/1dayRX0pzgR3TmoIz5M4FJRh8YpwA5WUx?usp=sharing

**Comment by aniketsingh98571** [comment]
@hkaur008 I think you need only the section which is below `collaborated with` text, right?

**Comment by hkaur008** [comment]
yes

**Comment by hkaur008** [comment]
we are just posting the new design !
