### ISSUE TITLE
on clicking home page there is a background in nav bar  but there is no nav bar at home page even there is no change in the content

### ISSUE THREAD

**Issue by Yashnatani021-coder** [CodeFlow201/codeflow#20]
https://user-images.githubusercontent.com/60621982/112970668-0fa68980-916c-11eb-9358-ab368f01abd3.mp4

**Comment by iamparasbansal** [comment]
This bug has been fixed

**Comment by iamparasbansal** [comment]
This Issue has arisen again by a faulty merge.
