### ISSUE TITLE
Landing Page fixing

### ISSUE THREAD

**Issue by nilesh-05** [CodeFlow201/codeflow#21]
The landing page gives a first impression of the organization. The homepage has a navbar which is half functional as it is not rendered on page load. Also, the blank space needs to be covered up. 

Also,there needs to be a footer with some content.

**Comment by Nirpendra09** [comment]
I am interested in this solving this issue. Please assign it to me.

**Comment by hkaur008** [comment]
we are actually coming up with a modified designs . Try to follow up and do modifications accordingly

**Comment by nilesh-05** [comment]
Why is this issue unassigned from me?

**Comment by vaibhavarora102** [comment]
@nilesh-05 , apologies for this miscommunication, you are now assigned for another issue, just work over there. and let this task be done by @Nirpendra09 
from just message 'Assign me' after opening issue, for more clarity
thanks
