### ISSUE TITLE
About Us Page

### ISSUE THREAD

**Issue by mostlypanda** [CodeFlow201/codeflow#25]
This will show our motive, aim as well as our methodology, So for designing this page keep these points in mind.

1. It will consist Codeflow's main image https://drive.google.com/drive/folders/1upgVWelM3pabjQ4GJ-yyb5aSMSfnJ6O3. You can take assets from this gdrive folder.
2. Along with the image our Name and tagline should be placed with some little transitions  to give it amazing appearance. And then some dummy text will be present after this that we will provide you after this designing. 

Try to use above points to design a great about us page for the community so that any user can have great view of our idealogy.

**Comment by VWRoli** [comment]
I would like to take this issue.

**Comment by mostlypanda** [comment]
That's great, @VWRoli  Just go ahead with the design.
