### ISSUE TITLE
Open Source Depiction

### ISSUE THREAD

**Issue by mostlypanda** [CodeFlow201/codeflow#26]
This will tell users about our efficiency and ability to provide opportunities in the field of open source. Keep these points in mind while designing this one.

1. Here we have to feature our all the on-going projects of our github profile. So figure out how you'll fetch that data of repositories on the Codeflow official github organisation.
2. Now comes the depiction, for this make a effective method like every repo will have a complete section where on left about it's name and info and after this links to go to code or to demo. and in the right picture depicting it's live demo. If any repo don't have such put readme photograph but make it fully animated and fascinated having transitions on hover and click.
3. Take care of bg-color.

**Comment by ShwetKhatri2001** [comment]
I would like to work on this issue, I have worked on GitHub API and demonstration of its repos already. https://github.com/ShwetKhatri2001/GetNextGit
