### ISSUE TITLE
Event page ideation

### ISSUE THREAD

**Issue by mostlypanda** [CodeFlow201/codeflow#3]
Start with this page because Codeflow is conducting a lot of events. 
So try to design that.
For design keep these points:
1.  For a latest event meaning the event is going to take place next. Try to make a big animated image slider for the same and then providing the links of it like fb, instagram, linkedin and the youtube too along with registration link.
2. After this show your successful conducted events.
3. And at last your upcoming events and these events thumbnails to be provided on the main page too

**Comment by iamparasbansal** [comment]
Events Page Designing is done.
