### ISSUE TITLE
NavBar 

### ISSUE THREAD

**Issue by KUMUDSHANDILYA** [CodeFlow201/codeflow#34]
![navbar](https://user-images.githubusercontent.com/55797140/113470366-a330d080-9472-11eb-98c3-18cae13ee235.jpeg)

The navbar should have links to following components:
1. Home 
2. Events
3. Hackathons
4. Open Source
5. Collaborations
visit #29  issue for complete homepage design

**Comment by thePlebDev** [comment]
If this issue is still open I would like to assigned. Thank you
