### ISSUE TITLE
About Us

### ISSUE THREAD

**Issue by KUMUDSHANDILYA** [CodeFlow201/codeflow#35]
The about us component should have a paragraph describing the organisation and three cards to depict major purposes of the organisation that are :
1. Opensource
2. Community Building
3. Events and workshop
![about](https://user-images.githubusercontent.com/55797140/113470522-eb9cbe00-9473-11eb-8a19-622555007e9c.jpeg)

visit #29  issue for complete homepage design

**Comment by MRrai111** [comment]
Assign me about us section.
#35
