### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by KUMUDSHANDILYA** [CodeFlow201/codeflow#36]
This section should have cards or other container to display testimonials.
The various cards should be displayed in a responsive carousel
![testiminials](https://user-images.githubusercontent.com/55797140/113470764-9cf02380-9475-11eb-9b08-fc11fb646760.jpeg)
 visit #29  issue for complete homepage design

**Comment by VWRoli** [comment]
Worked on this section, added a pull request.

**Comment by iamparasbansal** [comment]
@VWRoli This part is still not added. Are you working on this?

**Comment by VWRoli** [comment]
It's already merged.
"iamparasbansal merged commit 08b4961 into CodeFlow201:master 22 days ago"

**Comment by iamparasbansal** [comment]
But its not rendered. clone the master branch and run it on your local. See there is no testimonial section available. Please see to it!

**Comment by iamparasbansal** [comment]
But its not rendered. clone the master branch and run it on your local. See there is no testimonial section available.

**Comment by VWRoli** [comment]
Ohh, sorry. The homepage wasn't ready yet. I rendered it on the homepage and added a pull request.
