### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by KUMUDSHANDILYA** [CodeFlow201/codeflow#37]
The footer should contain the logo with the link to home page
It should have links to other section of the website as well that are:
1. Events
2. Hackathons
3. Open Source
4. Collaborations

Along with that, it should also have links to the social media handles of Codeflow as well
1. Facebook
2. Instagram
3. Linkedin
4. Twitter
5. Email
![footer](https://user-images.githubusercontent.com/55797140/113470872-459e8300-9476-11eb-98a2-a7306c5cebf2.jpeg)
visit #29  issue for complete homepage design

**Comment by VWRoli** [comment]
I would like to take this issue.

**Comment by mita13** [comment]
I would like to take this issue
