### ISSUE TITLE
Team section

### ISSUE THREAD

**Issue by KUMUDSHANDILYA** [CodeFlow201/codeflow#39]
The team section should be displaying an image and the name and designation of the core members of the organisation as depicted in the image.
It should also display the top contributors of the organisation
![team](https://user-images.githubusercontent.com/55797140/113470972-ef7e0f80-9476-11eb-94de-e3b2b5c4489e.jpeg)
visit #29  issue for complete homepage design

**Comment by Ayushgup85** [comment]
May i work on this issue?
