### ISSUE TITLE
Upcoming event card !!

### ISSUE THREAD

**Issue by hkaur008** [CodeFlow201/codeflow#42]
Upcoming event flash over here !
![Events Page part1 ](https://user-images.githubusercontent.com/56452820/113476691-96c06e00-949a-11eb-9350-4ee0f083835a.png)

visit #40  for complete details about this section . All assets are present in assets folder .
Use this gdrive assets folder Use this gdrive assets folder [assets folder](https://drive.google.com/drive/folders/1upgVWelM3pabjQ4GJ-yyb5aSMSfnJ6O3).

**Comment by Rishabhraghwendra18** [comment]
Hi.... . Do you want to get such looking card ?

**Comment by hkaur008** [comment]
yes

**Comment by Rishabhraghwendra18** [comment]
@hkaur008 may I work on this ?😍

**Comment by hkaur008** [comment]
sure !

> @hkaur008 may I work on this ?😍

**Comment by Rishabhraghwendra18** [comment]
@hkaur008 Thanks. Do you guys have discord ?

**Comment by hkaur008** [comment]
> @hkaur008 Thanks. Do you guys have discord ?

You join us on telegram currently it is restricted to team only !

**Comment by Rishabhraghwendra18** [comment]
@hkaur008 may you share the telegram link ?, because I am new to open source contribution and so that  I also can learn from you guys , because I have seen your profiles and it's amazing 🙇‍♂️

**Comment by hkaur008** [comment]
sure ! https://t.me/joinchat/HJvLCre4e001Yzdl

**Comment by Rishabhraghwendra18** [comment]
@hkaur008 Thanks
