### ISSUE TITLE
Add a section on "How to Update Your Github Forked Repository" in Readme file for beginners

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [CodeFlow201/codeflow#67]
I am thinking to add a section in Readme file called , "How to Update Your Github Forked Repository" . It will make easy for first timers to contribute to the repo .

**Comment by Rishabhraghwendra18** [comment]
May I work on this issue ?

**Comment by iamparasbansal** [comment]
I think there is no need to add this here because it is irrelevant to the current repository. This can be googled easily.

**Comment by Rishabhraghwendra18** [comment]
@iamparasbansal Ya..but for first timer I think it may be easy for him/her and GitMarkonics is also having this section , so I thought it will be useful here too 😅
