### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by hkaur008** [CodeFlow201/codeflow#8]

**Comment by aditya28sarin** [comment]
can you assign this issue to me?

**Comment by hkaur008** [comment]
ohk assigning you this issue .

**Comment by hkaur008** [comment]
ohk assigning you this issue .

**Comment by aditya28sarin** [comment]
I have updated the readme, you can merge the PR.

**Comment by hkaur008** [comment]
> I have updated the readme, you can merge the PR.

merged
