### ISSUE TITLE
Adding Material UI Icons

### ISSUE THREAD

**Issue by ekagrashukla** [CodeFlow201/codeflow#82]
Would like to add cool Material UI icons on navbar and footer, this will make the website look more minimal and professional, somewhat like this.

![image](https://user-images.githubusercontent.com/67453083/121769107-645c7c80-cb7f-11eb-8868-746c13fdb903.png)

If you find this useful, **please assign it to me**, as a participant of LGM SOC.

**Comment by Hardikpoudel** [comment]
I'ld like to work on this issue, as the LGM summer of code.

**Comment by rajgautam-cloud** [comment]
Can you assign me to add this feature

**Comment by KarishmaVanwari** [comment]
Hey @hkaur008 can I work on this issue for hacktoberfest 2021?

**Comment by hkaur008** [comment]
Sure you can

**Comment by KarishmaVanwari** [comment]
@hkaur008 have a look at my PR #107
