### ISSUE TITLE
Colorful Scrollbar Feature

### ISSUE THREAD

**Issue by ROHAN842** [CodeFlow201/codeflow#89]
I would like to design the scrollbar with linear gradient colors along with some animations, such that upon scrolling it looks dynamic and excellent.

I would like to work on this issue.

Kindly assign this issue to me under LGMSOC.

**Comment by ROHAN842** [comment]
Hey @iamparasbansal sir, @vaibhavarora102 sir and @hkaur008 ma'am please assign this issue to me.

**Comment by Aakash-Raj-2001** [comment]
@hkaur008 I want to work on this issue .Can you assign me this ?

**Comment by Aakash-Raj-2001** [comment]
@hkaur008 I solved this issue and commited the changes .Can you please check the PR  :)
