### ISSUE TITLE
Designing customized components 

### ISSUE THREAD

**Issue by mostlypanda** [CodeFlow201/codeflow#9]
Design following customized components for site:

1. Header to be present on every page at the top.
2. footer to be present everywhere
Remember one thing the theme should be same means the color bg that you will use to design anything should be  of same contrast to give it a more professional look.

To develop a image slider on frontpage that will include info about our event, about our aim, and photo gallery

**Comment by hkaur008** [comment]
1st part of issue completted !

**Comment by mostlypanda** [comment]
try to implement same header on every page and make sure about the stickiness of your header

**Comment by iamparasbansal** [comment]
Designing of Navbar and Footer is done! Rest can be discussed on individual issues opened.
